theme: jekyll-theme-cayman
title: timm walz
description: my personal page
twitter_username: nonstoptimm
github_username: nonstoptimm
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"