baseurl = "https://nonstoptimm.github.io" # Hostname (and path) to the root.
title = "timm walz" # Site title.
theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 10 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "timm walz" # Author's name.
    info = "data scientist @ microsoft" # Author's job title or info.
    description = "this is timm walz" # Site description.
    keywords = "blog,developer,personal,data scientist" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true
    hideFooter = false
    since = 2021

    footerContent = "one commit at a time."

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Color Scheme
    colorScheme = "auto"
    hideColorSchemeToggle = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/nonstoptimm/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/nonstoptimm/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/timmwalz/"
    
# Menu links
[[menu.main]]
    name = "about"
    weight = 1
    url  = "about"
[[menu.main]]
    name = "projects"
    weight = 2
    url = "projects"
[[menu.main]]
    name = "resume"
    weight = 2
    url = "resume"
